-- ================================================
-- dds.alarmlist  —  PLC RegisterAlarm ID 對照表
-- Generated: 2026-04-24 12:08
-- Rows: 399  |  Unique AlarmID: 133
-- ErrorID = PLC RegisterAlarm ID (HMI 看到的 Alarm.ID)
-- ================================================

delimiter $$

DROP TABLE IF EXISTS `alarmlist`$$

CREATE TABLE `alarmlist` (
  `index`   int(11)      NOT NULL,
  `ErrorID` varchar(200) DEFAULT NULL,
  `Type`    varchar(200) DEFAULT NULL,
  `Value`   varchar(200) DEFAULT NULL,
  PRIMARY KEY (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (1, '1', 'English', 'Allocate Estop has trig'),
  (2, '1', 'Chinese', '配针区急停已触发'),
  (3, '1', 'Taiwanese', '配針區急停已觸發'),
  (4, '2', 'English', 'Storage Estop has trig'),
  (5, '2', 'Chinese', '仓储区急停已触发'),
  (6, '2', 'Taiwanese', '倉儲區急停已觸發'),
  (7, '3', 'English', 'Storage robot Estop has trig'),
  (8, '3', 'Chinese', '仓储机器人急停已触发'),
  (9, '3', 'Taiwanese', '倉儲機器人急停已觸發'),
  (10, '4', 'English', 'Shipping robot Estop has trig'),
  (11, '4', 'Chinese', '出货机器人急停已触发'),
  (12, '4', 'Taiwanese', '出貨機器人急停已觸發'),
  (13, '5', 'English', 'Low AirPressure '),
  (14, '5', 'Chinese', '气压低'),
  (15, '5', 'Taiwanese', '氣壓低'),
  (16, '11', 'English', '(dynamic from fbMachineHoming.ErrorMsg)'),
  (17, '11', 'Chinese', '(動態: fbMachineHoming.ErrorMsg)'),
  (18, '11', 'Taiwanese', '(動態: fbMachineHoming.ErrorMsg)'),
  (19, '12', 'English', '(dynamic from fbStorageHoming.ErrorMsg)'),
  (20, '12', 'Chinese', '(動態: fbStorageHoming.ErrorMsg)'),
  (21, '12', 'Taiwanese', '(動態: fbStorageHoming.ErrorMsg)'),
  (22, '13', 'English', '(dynamic from fballocateHome.ErrorMsg)'),
  (23, '13', 'Chinese', '(動態: fballocateHome.ErrorMsg)'),
  (24, '13', 'Taiwanese', '(動態: fballocateHome.ErrorMsg)'),
  (25, '14', 'English', '(dynamic from fbShippingHoming.ErrorMsg)'),
  (26, '14', 'Chinese', '(動態: fbShippingHoming.ErrorMsg)'),
  (27, '14', 'Taiwanese', '(動態: fbShippingHoming.ErrorMsg)'),
  (28, '15', 'English', '(dynamic from TableMove.ErrorMsg)'),
  (29, '15', 'Chinese', '(動態: TableMove.ErrorMsg)'),
  (30, '15', 'Taiwanese', '(動態: TableMove.ErrorMsg)'),
  (31, '21', 'English', '(dynamic from fbReloadBox.Status)'),
  (32, '21', 'Chinese', '(動態: fbReloadBox.Status)'),
  (33, '21', 'Taiwanese', '(動態: fbReloadBox.Status)'),
  (34, '22', 'English', '(dynamic from fbFeedInBox.Status)'),
  (35, '22', 'Chinese', '(動態: fbFeedInBox.Status)'),
  (36, '22', 'Taiwanese', '(動態: fbFeedInBox.Status)'),
  (37, '23', 'English', '(dynamic from fbAddBoxes.Status)'),
  (38, '23', 'Chinese', '(動態: fbAddBoxes.Status)'),
  (39, '23', 'Taiwanese', '(動態: fbAddBoxes.Status)'),
  (40, '24', 'English', '(dynamic from fbBoxSupplyCtrl.Status)'),
  (41, '24', 'Chinese', '(動態: fbBoxSupplyCtrl.Status)'),
  (42, '24', 'Taiwanese', '(動態: fbBoxSupplyCtrl.Status)'),
  (43, '25', 'English', '(dynamic from fbFeedInEmptyBoxWithRobot.Status)'),
  (44, '25', 'Chinese', '(動態: fbFeedInEmptyBoxWithRobot.Status)'),
  (45, '25', 'Taiwanese', '(動態: fbFeedInEmptyBoxWithRobot.Status)'),
  (46, '26', 'English', '(dynamic from fbReloadRoundBeltBoxWithRobot.Status)'),
  (47, '26', 'Chinese', '(動態: fbReloadRoundBeltBoxWithRobot.Status)'),
  (48, '26', 'Taiwanese', '(動態: fbReloadRoundBeltBoxWithRobot.Status)'),
  (49, '27', 'English', '(dynamic from fbRobotAbsMove.Status)'),
  (50, '27', 'Chinese', '(動態: fbRobotAbsMove.Status)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (51, '27', 'Taiwanese', '(動態: fbRobotAbsMove.Status)'),
  (52, '28', 'English', '(dynamic from fbRobotRegionMove_AllocatedConveyor.Status)'),
  (53, '28', 'Chinese', '(動態: fbRobotRegionMove_AllocatedConveyor.Status)'),
  (54, '28', 'Taiwanese', '(動態: fbRobotRegionMove_AllocatedConveyor.Status)'),
  (55, '29', 'English', '(dynamic from fbRobotRegionMove_BufferArea.Status)'),
  (56, '29', 'Chinese', '(動態: fbRobotRegionMove_BufferArea.Status)'),
  (57, '29', 'Taiwanese', '(動態: fbRobotRegionMove_BufferArea.Status)'),
  (58, '30', 'English', '(dynamic from fbRobotRegionMove_FeedInConveyor.Status)'),
  (59, '30', 'Chinese', '(動態: fbRobotRegionMove_FeedInConveyor.Status)'),
  (60, '30', 'Taiwanese', '(動態: fbRobotRegionMove_FeedInConveyor.Status)'),
  (61, '31', 'English', '(dynamic from fbRobotRegionMove_PullOutConveyor.Status)'),
  (62, '31', 'Chinese', '(動態: fbRobotRegionMove_PullOutConveyor.Status)'),
  (63, '31', 'Taiwanese', '(動態: fbRobotRegionMove_PullOutConveyor.Status)'),
  (64, '32', 'English', '(dynamic from fbRobotRegionMove_RoundBelt.Status)'),
  (65, '32', 'Chinese', '(動態: fbRobotRegionMove_RoundBelt.Status)'),
  (66, '32', 'Taiwanese', '(動態: fbRobotRegionMove_RoundBelt.Status)'),
  (67, '33', 'English', '(dynamic from fbUpperFeedInConveyor.Status)'),
  (68, '33', 'Chinese', '(動態: fbUpperFeedInConveyor.Status)'),
  (69, '33', 'Taiwanese', '(動態: fbUpperFeedInConveyor.Status)'),
  (70, '34', 'English', '(dynamic from fbWareHouseWithRobotMove.Status)'),
  (71, '34', 'Chinese', '(動態: fbWareHouseWithRobotMove.Status)'),
  (72, '34', 'Taiwanese', '(動態: fbWareHouseWithRobotMove.Status)'),
  (73, '35', 'English', '(dynamic from fbWareHouseInnerPickToRoundBelt.Status)'),
  (74, '35', 'Chinese', '(動態: fbWareHouseInnerPickToRoundBelt.Status)'),
  (75, '35', 'Taiwanese', '(動態: fbWareHouseInnerPickToRoundBelt.Status)'),
  (76, '36', 'English', '(dynamic from fbWareHouseInnerPickToRoundBeltBatch.Status)'),
  (77, '36', 'Chinese', '(動態: fbWareHouseInnerPickToRoundBeltBatch.Status)'),
  (78, '36', 'Taiwanese', '(動態: fbWareHouseInnerPickToRoundBeltBatch.Status)'),
  (79, '38', 'English', '(dynamic from fbRobotSelfHoming.Status)'),
  (80, '38', 'Chinese', '(動態: fbRobotSelfHoming.Status)'),
  (81, '38', 'Taiwanese', '(動態: fbRobotSelfHoming.Status)'),
  (82, '39', 'English', '(dynamic from fbFeedInRoundBeltBoxBatch.Status)'),
  (83, '39', 'Chinese', '(動態: fbFeedInRoundBeltBoxBatch.Status)'),
  (84, '39', 'Taiwanese', '(動態: fbFeedInRoundBeltBoxBatch.Status)'),
  (85, '40', 'English', '(dynamic from fbFeedInRoundBeltBoxToWareHouse.Status)'),
  (86, '40', 'Chinese', '(動態: fbFeedInRoundBeltBoxToWareHouse.Status)'),
  (87, '40', 'Taiwanese', '(動態: fbFeedInRoundBeltBoxToWareHouse.Status)'),
  (88, '50', 'English', '(dynamic from fb_AllocateBatchMode.Status)'),
  (89, '50', 'Chinese', '(動態: fb_AllocateBatchMode.Status)'),
  (90, '50', 'Taiwanese', '(動態: fb_AllocateBatchMode.Status)'),
  (91, '51', 'English', '(dynamic from fb_AllocateBatchMode_Reverse.Status)'),
  (92, '51', 'Chinese', '(動態: fb_AllocateBatchMode_Reverse.Status)'),
  (93, '51', 'Taiwanese', '(動態: fb_AllocateBatchMode_Reverse.Status)'),
  (94, '52', 'English', '(dynamic from fbDifferentCVCamera.ErrorMsg)'),
  (95, '52', 'Chinese', '(動態: fbDifferentCVCamera.ErrorMsg)'),
  (96, '52', 'Taiwanese', '(動態: fbDifferentCVCamera.ErrorMsg)'),
  (97, '53', 'English', '(dynamic from fbOutRobot_BoxMoveReverse.Status)'),
  (98, '53', 'Chinese', '(動態: fbOutRobot_BoxMoveReverse.Status)'),
  (99, '53', 'Taiwanese', '(動態: fbOutRobot_BoxMoveReverse.Status)'),
  (100, '54', 'English', '(dynamic from fbOutRobot_EmptyBoxMove.Status)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (101, '54', 'Chinese', '(動態: fbOutRobot_EmptyBoxMove.Status)'),
  (102, '54', 'Taiwanese', '(動態: fbOutRobot_EmptyBoxMove.Status)'),
  (103, '55', 'English', '(dynamic from fbOutRobot_RareBoxMove.Status)'),
  (104, '55', 'Chinese', '(動態: fbOutRobot_RareBoxMove.Status)'),
  (105, '55', 'Taiwanese', '(動態: fbOutRobot_RareBoxMove.Status)'),
  (106, '56', 'English', '(dynamic from fbPulloutCV.Status)'),
  (107, '56', 'Chinese', '(動態: fbPulloutCV.Status)'),
  (108, '56', 'Taiwanese', '(動態: fbPulloutCV.Status)'),
  (109, '57', 'English', '(dynamic from RoundBeltControl.ErrorMsg)'),
  (110, '57', 'Chinese', '(動態: RoundBeltControl.ErrorMsg)'),
  (111, '57', 'Taiwanese', '(動態: RoundBeltControl.ErrorMsg)'),
  (112, '58', 'English', '(dynamic from fbSameSizeCVCamera.ErrorMsg)'),
  (113, '58', 'Chinese', '(動態: fbSameSizeCVCamera.ErrorMsg)'),
  (114, '58', 'Taiwanese', '(動態: fbSameSizeCVCamera.ErrorMsg)'),
  (115, '59', 'English', '(dynamic from TurnTableControl.ErrorMsg)'),
  (116, '59', 'Chinese', '(動態: TurnTableControl.ErrorMsg)'),
  (117, '59', 'Taiwanese', '(動態: TurnTableControl.ErrorMsg)'),
  (118, '60', 'English', '(dynamic from fbOutRobot_TurnTableToRoundBelt.Status)'),
  (119, '60', 'Chinese', '(動態: fbOutRobot_TurnTableToRoundBelt.Status)'),
  (120, '60', 'Taiwanese', '(動態: fbOutRobot_TurnTableToRoundBelt.Status)'),
  (121, '61', 'English', '(dynamic from fbAllocateRobotNeedlingMove.ErrorMsg)'),
  (122, '61', 'Chinese', '(動態: fbAllocateRobotNeedlingMove.ErrorMsg)'),
  (123, '61', 'Taiwanese', '(動態: fbAllocateRobotNeedlingMove.ErrorMsg)'),
  (124, '62', 'English', '(dynamic from fbSameSizeCVCamera_Reverse.ErrorMsg)'),
  (125, '62', 'Chinese', '(動態: fbSameSizeCVCamera_Reverse.ErrorMsg)'),
  (126, '62', 'Taiwanese', '(動態: fbSameSizeCVCamera_Reverse.ErrorMsg)'),
  (127, '63', 'English', '(dynamic from fbReverseBoxToWareHouse.Status)'),
  (128, '63', 'Chinese', '(動態: fbReverseBoxToWareHouse.Status)'),
  (129, '63', 'Taiwanese', '(動態: fbReverseBoxToWareHouse.Status)'),
  (130, '64', 'English', '(dynamic from fbReverseBatchPickAndPhoto.Status)'),
  (131, '64', 'Chinese', '(動態: fbReverseBatchPickAndPhoto.Status)'),
  (132, '64', 'Taiwanese', '(動態: fbReverseBatchPickAndPhoto.Status)'),
  (133, '80', 'English', '(dynamic from fbShippingRobot_Left.Status)'),
  (134, '80', 'Chinese', '(動態: fbShippingRobot_Left.Status)'),
  (135, '80', 'Taiwanese', '(動態: fbShippingRobot_Left.Status)'),
  (136, '81', 'English', '(dynamic from fbShippingRobot_Right.Status)'),
  (137, '81', 'Chinese', '(動態: fbShippingRobot_Right.Status)'),
  (138, '81', 'Taiwanese', '(動態: fbShippingRobot_Right.Status)'),
  (139, '82', 'English', '(dynamic from fbShippingRobot_TransmitCVEnd.Status)'),
  (140, '82', 'Chinese', '(動態: fbShippingRobot_TransmitCVEnd.Status)'),
  (141, '82', 'Taiwanese', '(動態: fbShippingRobot_TransmitCVEnd.Status)'),
  (142, '83', 'English', '(dynamic from fbShippingLeftSideTransCV.ErrorMsg)'),
  (143, '83', 'Chinese', '(動態: fbShippingLeftSideTransCV.ErrorMsg)'),
  (144, '83', 'Taiwanese', '(動態: fbShippingLeftSideTransCV.ErrorMsg)'),
  (145, '84', 'English', '(dynamic from fbShippingRightSideTransCV.ErrorMsg)'),
  (146, '84', 'Chinese', '(動態: fbShippingRightSideTransCV.ErrorMsg)'),
  (147, '84', 'Taiwanese', '(動態: fbShippingRightSideTransCV.ErrorMsg)'),
  (148, '85', 'English', '(dynamic from fbShippingRobotTransfer.Status)'),
  (149, '85', 'Chinese', '(動態: fbShippingRobotTransfer.Status)'),
  (150, '85', 'Taiwanese', '(動態: fbShippingRobotTransfer.Status)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (151, '86', 'English', '(dynamic from fbShippingRobot_Buffer.Status)'),
  (152, '86', 'Chinese', '(動態: fbShippingRobot_Buffer.Status)'),
  (153, '86', 'Taiwanese', '(動態: fbShippingRobot_Buffer.Status)'),
  (154, '87', 'English', '(dynamic from fbShippingRobot_PhotoStandByPos.Status)'),
  (155, '87', 'Chinese', '(動態: fbShippingRobot_PhotoStandByPos.Status)'),
  (156, '87', 'Taiwanese', '(動態: fbShippingRobot_PhotoStandByPos.Status)'),
  (157, '101', 'English', '(dynamic from fbAllocateRobot_LeftClamp1.ErrorMsg)'),
  (158, '101', 'Chinese', '(動態: fbAllocateRobot_LeftClamp1.ErrorMsg)'),
  (159, '101', 'Taiwanese', '(動態: fbAllocateRobot_LeftClamp1.ErrorMsg)'),
  (160, '102', 'English', '(dynamic from fbAllocateRobot_LeftClamp2.ErrorMsg)'),
  (161, '102', 'Chinese', '(動態: fbAllocateRobot_LeftClamp2.ErrorMsg)'),
  (162, '102', 'Taiwanese', '(動態: fbAllocateRobot_LeftClamp2.ErrorMsg)'),
  (163, '103', 'English', '(dynamic from fbAllocateRobot_LeftVert1.ErrorMsg)'),
  (164, '103', 'Chinese', '(動態: fbAllocateRobot_LeftVert1.ErrorMsg)'),
  (165, '103', 'Taiwanese', '(動態: fbAllocateRobot_LeftVert1.ErrorMsg)'),
  (166, '104', 'English', '(dynamic from fbAllocateRobot_LeftVert2.ErrorMsg)'),
  (167, '104', 'Chinese', '(動態: fbAllocateRobot_LeftVert2.ErrorMsg)'),
  (168, '104', 'Taiwanese', '(動態: fbAllocateRobot_LeftVert2.ErrorMsg)'),
  (169, '105', 'English', '(dynamic from fbAllocateRobot_RightClamp1.ErrorMsg)'),
  (170, '105', 'Chinese', '(動態: fbAllocateRobot_RightClamp1.ErrorMsg)'),
  (171, '105', 'Taiwanese', '(動態: fbAllocateRobot_RightClamp1.ErrorMsg)'),
  (172, '106', 'English', '(dynamic from fbAllocateRobot_RightClamp2.ErrorMsg)'),
  (173, '106', 'Chinese', '(動態: fbAllocateRobot_RightClamp2.ErrorMsg)'),
  (174, '106', 'Taiwanese', '(動態: fbAllocateRobot_RightClamp2.ErrorMsg)'),
  (175, '107', 'English', '(dynamic from fbAllocateRobot_RightVert1.ErrorMsg)'),
  (176, '107', 'Chinese', '(動態: fbAllocateRobot_RightVert1.ErrorMsg)'),
  (177, '107', 'Taiwanese', '(動態: fbAllocateRobot_RightVert1.ErrorMsg)'),
  (178, '108', 'English', '(dynamic from fbAllocateRobot_RightVert2.ErrorMsg)'),
  (179, '108', 'Chinese', '(動態: fbAllocateRobot_RightVert2.ErrorMsg)'),
  (180, '108', 'Taiwanese', '(動態: fbAllocateRobot_RightVert2.ErrorMsg)'),
  (181, '110', 'English', '(dynamic from fbRoundBelt_WorkZone_Press.ErrorMsg)'),
  (182, '110', 'Chinese', '(動態: fbRoundBelt_WorkZone_Press.ErrorMsg)'),
  (183, '110', 'Taiwanese', '(動態: fbRoundBelt_WorkZone_Press.ErrorMsg)'),
  (184, '111', 'English', '(dynamic from fbRoundBelt_WorkZone_Plug.ErrorMsg)'),
  (185, '111', 'Chinese', '(動態: fbRoundBelt_WorkZone_Plug.ErrorMsg)'),
  (186, '111', 'Taiwanese', '(動態: fbRoundBelt_WorkZone_Plug.ErrorMsg)'),
  (187, '112', 'English', '(dynamic from fbRoundBelt_ChargeZone_Plug.ErrorMsg)'),
  (188, '112', 'Chinese', '(動態: fbRoundBelt_ChargeZone_Plug.ErrorMsg)'),
  (189, '112', 'Taiwanese', '(動態: fbRoundBelt_ChargeZone_Plug.ErrorMsg)'),
  (190, '113', 'English', '(dynamic from fbRoundBelt_TransmitCVZone_Plug.ErrorMsg)'),
  (191, '113', 'Chinese', '(動態: fbRoundBelt_TransmitCVZone_Plug.ErrorMsg)'),
  (192, '113', 'Taiwanese', '(動態: fbRoundBelt_TransmitCVZone_Plug.ErrorMsg)'),
  (193, '114', 'English', '(dynamic from fbOutRobot_AsideVert.ErrorMsg)'),
  (194, '114', 'Chinese', '(動態: fbOutRobot_AsideVert.ErrorMsg)'),
  (195, '114', 'Taiwanese', '(動態: fbOutRobot_AsideVert.ErrorMsg)'),
  (196, '115', 'English', '(dynamic from fbOutRobot_BsideVert.ErrorMsg)'),
  (197, '115', 'Chinese', '(動態: fbOutRobot_BsideVert.ErrorMsg)'),
  (198, '115', 'Taiwanese', '(動態: fbOutRobot_BsideVert.ErrorMsg)'),
  (199, '116', 'English', '(dynamic from fbOutRobot_AsideClamp.ErrorMsg)'),
  (200, '116', 'Chinese', '(動態: fbOutRobot_AsideClamp.ErrorMsg)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (201, '116', 'Taiwanese', '(動態: fbOutRobot_AsideClamp.ErrorMsg)'),
  (202, '117', 'English', '(dynamic from fbOutRobot_BsideClamp.ErrorMsg)'),
  (203, '117', 'Chinese', '(動態: fbOutRobot_BsideClamp.ErrorMsg)'),
  (204, '117', 'Taiwanese', '(動態: fbOutRobot_BsideClamp.ErrorMsg)'),
  (205, '118', 'English', '(dynamic from fbTransmitCV_CamaraHoriz.ErrorMsg)'),
  (206, '118', 'Chinese', '(動態: fbTransmitCV_CamaraHoriz.ErrorMsg)'),
  (207, '118', 'Taiwanese', '(動態: fbTransmitCV_CamaraHoriz.ErrorMsg)'),
  (208, '119', 'English', '(dynamic from fbDifferentSizeCV_Press2.ErrorMsg)'),
  (209, '119', 'Chinese', '(動態: fbDifferentSizeCV_Press2.ErrorMsg)'),
  (210, '119', 'Taiwanese', '(動態: fbDifferentSizeCV_Press2.ErrorMsg)'),
  (211, '120', 'English', '(dynamic from fbDifferentSizeCV_Press1.ErrorMsg)'),
  (212, '120', 'Chinese', '(動態: fbDifferentSizeCV_Press1.ErrorMsg)'),
  (213, '120', 'Taiwanese', '(動態: fbDifferentSizeCV_Press1.ErrorMsg)'),
  (214, '121', 'English', '(dynamic from fbDifferentSizeCV_Block1.ErrorMsg)'),
  (215, '121', 'Chinese', '(動態: fbDifferentSizeCV_Block1.ErrorMsg)'),
  (216, '121', 'Taiwanese', '(動態: fbDifferentSizeCV_Block1.ErrorMsg)'),
  (217, '122', 'English', '(dynamic from fbSameSizeCV_Press4.ErrorMsg)'),
  (218, '122', 'Chinese', '(動態: fbSameSizeCV_Press4.ErrorMsg)'),
  (219, '122', 'Taiwanese', '(動態: fbSameSizeCV_Press4.ErrorMsg)'),
  (220, '123', 'English', '(dynamic from fbSameSizeCV_Press3.ErrorMsg)'),
  (221, '123', 'Chinese', '(動態: fbSameSizeCV_Press3.ErrorMsg)'),
  (222, '123', 'Taiwanese', '(動態: fbSameSizeCV_Press3.ErrorMsg)'),
  (223, '124', 'English', '(dynamic from fbSameSizeCV_Press2.ErrorMsg)'),
  (224, '124', 'Chinese', '(動態: fbSameSizeCV_Press2.ErrorMsg)'),
  (225, '124', 'Taiwanese', '(動態: fbSameSizeCV_Press2.ErrorMsg)'),
  (226, '125', 'English', '(dynamic from fbSameSizeCV_Press1.ErrorMsg)'),
  (227, '125', 'Chinese', '(動態: fbSameSizeCV_Press1.ErrorMsg)'),
  (228, '125', 'Taiwanese', '(動態: fbSameSizeCV_Press1.ErrorMsg)'),
  (229, '126', 'English', '(dynamic from fbSameSizeCV_Block2.ErrorMsg)'),
  (230, '126', 'Chinese', '(動態: fbSameSizeCV_Block2.ErrorMsg)'),
  (231, '126', 'Taiwanese', '(動態: fbSameSizeCV_Block2.ErrorMsg)'),
  (232, '127', 'English', '(dynamic from fbSameSizeCV_Block1.ErrorMsg)'),
  (233, '127', 'Chinese', '(動態: fbSameSizeCV_Block1.ErrorMsg)'),
  (234, '127', 'Taiwanese', '(動態: fbSameSizeCV_Block1.ErrorMsg)'),
  (235, '128', 'English', '(dynamic from fbPullOutCV_AsidePress1.ErrorMsg)'),
  (236, '128', 'Chinese', '(動態: fbPullOutCV_AsidePress1.ErrorMsg)'),
  (237, '128', 'Taiwanese', '(動態: fbPullOutCV_AsidePress1.ErrorMsg)'),
  (238, '129', 'English', '(dynamic from fbPullOutCV_AsidePress2.ErrorMsg)'),
  (239, '129', 'Chinese', '(動態: fbPullOutCV_AsidePress2.ErrorMsg)'),
  (240, '129', 'Taiwanese', '(動態: fbPullOutCV_AsidePress2.ErrorMsg)'),
  (241, '130', 'English', '(dynamic from fbPullOutCV_AsideBlock.ErrorMsg)'),
  (242, '130', 'Chinese', '(動態: fbPullOutCV_AsideBlock.ErrorMsg)'),
  (243, '130', 'Taiwanese', '(動態: fbPullOutCV_AsideBlock.ErrorMsg)'),
  (244, '131', 'English', '(dynamic from fbPullOutCV_BsidePress1.ErrorMsg)'),
  (245, '131', 'Chinese', '(動態: fbPullOutCV_BsidePress1.ErrorMsg)'),
  (246, '131', 'Taiwanese', '(動態: fbPullOutCV_BsidePress1.ErrorMsg)'),
  (247, '132', 'English', '(dynamic from fbPullOutCV_BsidePress2.ErrorMsg)'),
  (248, '132', 'Chinese', '(動態: fbPullOutCV_BsidePress2.ErrorMsg)'),
  (249, '132', 'Taiwanese', '(動態: fbPullOutCV_BsidePress2.ErrorMsg)'),
  (250, '133', 'English', '(dynamic from fbPullOutCV_BsideBlock.ErrorMsg)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (251, '133', 'Chinese', '(動態: fbPullOutCV_BsideBlock.ErrorMsg)'),
  (252, '133', 'Taiwanese', '(動態: fbPullOutCV_BsideBlock.ErrorMsg)'),
  (253, '134', 'English', '(dynamic from fbUpCV_FeedInPress1.ErrorMsg)'),
  (254, '134', 'Chinese', '(動態: fbUpCV_FeedInPress1.ErrorMsg)'),
  (255, '134', 'Taiwanese', '(動態: fbUpCV_FeedInPress1.ErrorMsg)'),
  (256, '135', 'English', '(dynamic from fbUpCV_FeedInPress2.ErrorMsg)'),
  (257, '135', 'Chinese', '(動態: fbUpCV_FeedInPress2.ErrorMsg)'),
  (258, '135', 'Taiwanese', '(動態: fbUpCV_FeedInPress2.ErrorMsg)'),
  (259, '136', 'English', '(dynamic from fbUpCV_DiameterPress.ErrorMsg)'),
  (260, '136', 'Chinese', '(動態: fbUpCV_DiameterPress.ErrorMsg)'),
  (261, '136', 'Taiwanese', '(動態: fbUpCV_DiameterPress.ErrorMsg)'),
  (262, '137', 'English', '(dynamic from fbUpCV_CamaraPress1.ErrorMsg)'),
  (263, '137', 'Chinese', '(動態: fbUpCV_CamaraPress1.ErrorMsg)'),
  (264, '137', 'Taiwanese', '(動態: fbUpCV_CamaraPress1.ErrorMsg)'),
  (265, '138', 'English', '(dynamic from fbUpCV_CamaraPress2.ErrorMsg)'),
  (266, '138', 'Chinese', '(動態: fbUpCV_CamaraPress2.ErrorMsg)'),
  (267, '138', 'Taiwanese', '(動態: fbUpCV_CamaraPress2.ErrorMsg)'),
  (268, '139', 'English', '(dynamic from fbUpCV_CamaraPress3.ErrorMsg)'),
  (269, '139', 'Chinese', '(動態: fbUpCV_CamaraPress3.ErrorMsg)'),
  (270, '139', 'Taiwanese', '(動態: fbUpCV_CamaraPress3.ErrorMsg)'),
  (271, '140', 'English', '(dynamic from fbUpCV_CamaraPress4.ErrorMsg)'),
  (272, '140', 'Chinese', '(動態: fbUpCV_CamaraPress4.ErrorMsg)'),
  (273, '140', 'Taiwanese', '(動態: fbUpCV_CamaraPress4.ErrorMsg)'),
  (274, '141', 'English', '(dynamic from fbUpCV_Block1.ErrorMsg)'),
  (275, '141', 'Chinese', '(動態: fbUpCV_Block1.ErrorMsg)'),
  (276, '141', 'Taiwanese', '(動態: fbUpCV_Block1.ErrorMsg)'),
  (277, '142', 'English', '(dynamic from fbUpCV_Block2.ErrorMsg)'),
  (278, '142', 'Chinese', '(動態: fbUpCV_Block2.ErrorMsg)'),
  (279, '142', 'Taiwanese', '(動態: fbUpCV_Block2.ErrorMsg)'),
  (280, '143', 'English', '(dynamic from fbUpCV_Block3.ErrorMsg)'),
  (281, '143', 'Chinese', '(動態: fbUpCV_Block3.ErrorMsg)'),
  (282, '143', 'Taiwanese', '(動態: fbUpCV_Block3.ErrorMsg)'),
  (283, '144', 'English', '(dynamic from fbUpCV_DiameterHoriz.ErrorMsg)'),
  (284, '144', 'Chinese', '(動態: fbUpCV_DiameterHoriz.ErrorMsg)'),
  (285, '144', 'Taiwanese', '(動態: fbUpCV_DiameterHoriz.ErrorMsg)'),
  (286, '145', 'English', '(dynamic from fbUpCV_DiameterVert.ErrorMsg)'),
  (287, '145', 'Chinese', '(動態: fbUpCV_DiameterVert.ErrorMsg)'),
  (288, '145', 'Taiwanese', '(動態: fbUpCV_DiameterVert.ErrorMsg)'),
  (289, '146', 'English', '(dynamic from fbUpCV_DiameterClamp.ErrorMsg)'),
  (290, '146', 'Chinese', '(動態: fbUpCV_DiameterClamp.ErrorMsg)'),
  (291, '146', 'Taiwanese', '(動態: fbUpCV_DiameterClamp.ErrorMsg)'),
  (292, '147', 'English', '(dynamic from fbStackPush.ErrorMsg)'),
  (293, '147', 'Chinese', '(動態: fbStackPush.ErrorMsg)'),
  (294, '147', 'Taiwanese', '(動態: fbStackPush.ErrorMsg)'),
  (295, '148', 'English', '(dynamic from fbLowCV_Press1.ErrorMsg)'),
  (296, '148', 'Chinese', '(動態: fbLowCV_Press1.ErrorMsg)'),
  (297, '148', 'Taiwanese', '(動態: fbLowCV_Press1.ErrorMsg)'),
  (298, '149', 'English', '(dynamic from fbLowCV_Press2.ErrorMsg)'),
  (299, '149', 'Chinese', '(動態: fbLowCV_Press2.ErrorMsg)'),
  (300, '149', 'Taiwanese', '(動態: fbLowCV_Press2.ErrorMsg)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (301, '150', 'English', '(dynamic from fbLowCV_Press3.ErrorMsg)'),
  (302, '150', 'Chinese', '(動態: fbLowCV_Press3.ErrorMsg)'),
  (303, '150', 'Taiwanese', '(動態: fbLowCV_Press3.ErrorMsg)'),
  (304, '151', 'English', '(dynamic from fbLowCV_Press4.ErrorMsg)'),
  (305, '151', 'Chinese', '(動態: fbLowCV_Press4.ErrorMsg)'),
  (306, '151', 'Taiwanese', '(動態: fbLowCV_Press4.ErrorMsg)'),
  (307, '152', 'English', '(dynamic from fbLowCV_Block1.ErrorMsg)'),
  (308, '152', 'Chinese', '(動態: fbLowCV_Block1.ErrorMsg)'),
  (309, '152', 'Taiwanese', '(動態: fbLowCV_Block1.ErrorMsg)'),
  (310, '153', 'English', '(dynamic from fbLowCV_Block2.ErrorMsg)'),
  (311, '153', 'Chinese', '(動態: fbLowCV_Block2.ErrorMsg)'),
  (312, '153', 'Taiwanese', '(動態: fbLowCV_Block2.ErrorMsg)'),
  (313, '158', 'English', '(dynamic from StorageRobot.ErrMsg)'),
  (314, '158', 'Chinese', '(動態: StorageRobot.ErrMsg)'),
  (315, '158', 'Taiwanese', '(動態: StorageRobot.ErrMsg)'),
  (316, '159', 'English', '(dynamic from ShippingRobot.ErrMsg)'),
  (317, '159', 'Chinese', '(動態: ShippingRobot.ErrMsg)'),
  (318, '159', 'Taiwanese', '(動態: ShippingRobot.ErrMsg)'),
  (319, '201', 'English', 'TurnTable axis has Error'),
  (320, '201', 'Chinese', 'TurnTable 轴有错误'),
  (321, '201', 'Taiwanese', 'TurnTable 軸有錯誤'),
  (322, '202', 'English', 'Roundbelt axis has Error'),
  (323, '202', 'Chinese', 'Roundbelt 轴有错误'),
  (324, '202', 'Taiwanese', 'Roundbelt 軸有錯誤'),
  (325, '203', 'English', 'Allocate_X axis has Error'),
  (326, '203', 'Chinese', 'Allocate_X 轴有错误'),
  (327, '203', 'Taiwanese', 'Allocate_X 軸有錯誤'),
  (328, '204', 'English', 'Allocate_Y axis has Error'),
  (329, '204', 'Chinese', 'Allocate_Y 轴有错误'),
  (330, '204', 'Taiwanese', 'Allocate_Y 軸有錯誤'),
  (331, '205', 'English', 'OutRobot_X axis has Error'),
  (332, '205', 'Chinese', 'OutRobot_X 轴有错误'),
  (333, '205', 'Taiwanese', 'OutRobot_X 軸有錯誤'),
  (334, '206', 'English', 'OutRobot_Y axis has Error'),
  (335, '206', 'Chinese', 'OutRobot_Y 轴有错误'),
  (336, '206', 'Taiwanese', 'OutRobot_Y 軸有錯誤'),
  (337, '207', 'English', 'RackMotor axis has Error'),
  (338, '207', 'Chinese', 'RackMotor 轴有错误'),
  (339, '207', 'Taiwanese', 'RackMotor 軸有錯誤'),
  (340, '300', 'English', '(dynamic from RS485_V2.ErrorMsg)'),
  (341, '300', 'Chinese', '(動態: RS485_V2.ErrorMsg)'),
  (342, '300', 'Taiwanese', '(動態: RS485_V2.ErrorMsg)'),
  (343, '301', 'English', '(dynamic from RS485_V2.ErrorMsg)'),
  (344, '301', 'Chinese', '(動態: RS485_V2.ErrorMsg)'),
  (345, '301', 'Taiwanese', '(動態: RS485_V2.ErrorMsg)'),
  (346, '302', 'English', '(dynamic from RS485_V2.ErrorMsg)'),
  (347, '302', 'Chinese', '(動態: RS485_V2.ErrorMsg)'),
  (348, '302', 'Taiwanese', '(動態: RS485_V2.ErrorMsg)'),
  (349, '303', 'English', '(dynamic from RS485_V2.ErrorMsg)'),
  (350, '303', 'Chinese', '(動態: RS485_V2.ErrorMsg)')$$

INSERT INTO `alarmlist` (`index`, `ErrorID`, `Type`, `Value`) VALUES
  (351, '303', 'Taiwanese', '(動態: RS485_V2.ErrorMsg)'),
  (352, '401', 'English', 'Safe door1  Opened'),
  (353, '401', 'Chinese', '安全门1 已开启'),
  (354, '401', 'Taiwanese', '安全門1 已開啟'),
  (355, '402', 'English', 'Safe door2  Opened'),
  (356, '402', 'Chinese', '安全门2 已开启'),
  (357, '402', 'Taiwanese', '安全門2 已開啟'),
  (358, '403', 'English', 'Safe door3  Opened'),
  (359, '403', 'Chinese', '安全门3 已开启'),
  (360, '403', 'Taiwanese', '安全門3 已開啟'),
  (361, '404', 'English', 'Safe door4  Opened'),
  (362, '404', 'Chinese', '安全门4 已开启'),
  (363, '404', 'Taiwanese', '安全門4 已開啟'),
  (364, '405', 'English', 'Safe door5  Opened'),
  (365, '405', 'Chinese', '安全门5 已开启'),
  (366, '405', 'Taiwanese', '安全門5 已開啟'),
  (367, '406', 'English', 'Safe door6  Opened'),
  (368, '406', 'Chinese', '安全门6 已开启'),
  (369, '406', 'Taiwanese', '安全門6 已開啟'),
  (370, '407', 'English', 'Safe door7  Opened'),
  (371, '407', 'Chinese', '安全门7 已开启'),
  (372, '407', 'Taiwanese', '安全門7 已開啟'),
  (373, '408', 'English', 'Safe door8  Opened'),
  (374, '408', 'Chinese', '安全门8 已开启'),
  (375, '408', 'Taiwanese', '安全門8 已開啟'),
  (376, '409', 'English', 'Safe door9  Opened'),
  (377, '409', 'Chinese', '安全门9 已开启'),
  (378, '409', 'Taiwanese', '安全門9 已開啟'),
  (379, '410', 'English', 'Safe door10  Opened'),
  (380, '410', 'Chinese', '安全门10 已开启'),
  (381, '410', 'Taiwanese', '安全門10 已開啟'),
  (382, '411', 'English', 'Safe door11  Opened'),
  (383, '411', 'Chinese', '安全门11 已开启'),
  (384, '411', 'Taiwanese', '安全門11 已開啟'),
  (385, '412', 'English', 'Safe doo12  Opened'),
  (386, '412', 'Chinese', '安全门12 已开启 (PLC字串拼写typo: doo12)'),
  (387, '412', 'Taiwanese', '安全門12 已開啟 (PLC字串拼寫typo: doo12)'),
  (388, '413', 'English', 'Safe doo13  Opened'),
  (389, '413', 'Chinese', '安全门13 已开启 (PLC字串拼写typo: doo13)'),
  (390, '413', 'Taiwanese', '安全門13 已開啟 (PLC字串拼寫typo: doo13)'),
  (391, '414', 'English', 'Safe door14  Opened'),
  (392, '414', 'Chinese', '安全门14 已开启'),
  (393, '414', 'Taiwanese', '安全門14 已開啟'),
  (394, '415', 'English', 'Allocate_Electrical_Cabinet_SafetyDoor  Opened'),
  (395, '415', 'Chinese', '配针区电箱安全门已开启'),
  (396, '415', 'Taiwanese', '配針區電箱安全門已開啟'),
  (397, '416', 'English', 'bShippingRobot_ElectricalCabinet_SafetyDoor  Opened'),
  (398, '416', 'Chinese', '出货机器人电箱安全门已开启'),
  (399, '416', 'Taiwanese', '出貨機器人電箱安全門已開啟')$$

delimiter ;
